# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto_generated.voice_agent_transport_pb2 as voice__agent__transport__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in voice_agent_transport_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceAgentTransportStub(object):
    """Voice transport service for bidirectional streaming of audio and data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Stream = channel.stream_stream(
                '/grpc.voice.agent.VoiceAgentTransport/Stream',
                request_serializer=voice__agent__transport__pb2.StreamMessage.SerializeToString,
                response_deserializer=voice__agent__transport__pb2.StreamMessage.FromString,
                _registered_method=True)


class VoiceAgentTransportServicer(object):
    """Voice transport service for bidirectional streaming of audio and data
    """

    def Stream(self, request_iterator, context):
        """Bidirectional streaming for audio and data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceAgentTransportServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Stream': grpc.stream_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=voice__agent__transport__pb2.StreamMessage.FromString,
                    response_serializer=voice__agent__transport__pb2.StreamMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.voice.agent.VoiceAgentTransport', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc.voice.agent.VoiceAgentTransport', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceAgentTransport(object):
    """Voice transport service for bidirectional streaming of audio and data
    """

    @staticmethod
    def Stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/grpc.voice.agent.VoiceAgentTransport/Stream',
            voice__agent__transport__pb2.StreamMessage.SerializeToString,
            voice__agent__transport__pb2.StreamMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
