# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voice_agent_transport.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'voice_agent_transport.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bvoice_agent_transport.proto\x12\x10grpc.voice.agent\x1a\x1cgoogle/protobuf/struct.proto\"Q\n\rStreamMessage\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0b\n\x03raw\x18\x02 \x01(\x0c\x12%\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct2e\n\x13VoiceAgentTransport\x12N\n\x06Stream\x12\x1f.grpc.voice.agent.StreamMessage\x1a\x1f.grpc.voice.agent.StreamMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_agent_transport_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMMESSAGE']._serialized_start=79
  _globals['_STREAMMESSAGE']._serialized_end=160
  _globals['_VOICEAGENTTRANSPORT']._serialized_start=162
  _globals['_VOICEAGENTTRANSPORT']._serialized_end=263
# @@protoc_insertion_point(module_scope)
